name: Deploy .NET app to GCP

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: Deploy application to GKE
    runs-on: self-hosted   # Use GCP-hosted runner or self-hosted if preferred

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: docker buildx build --platform linux/arm64 -t githubactions-gke-demo:'${{ github.sha }}' .

      - name: Tag and push Docker image to GCR
        run: |
          docker tag githubactions-gke-demo:'${{ github.sha }}' gcr.io/${{ secrets.GCP_PROJECT_ID }}/githubactions-gke-demo:'${{ github.sha }}'
          docker push gcr.io/astral-subject-452906-a1/githubactions-gke-demo:'${{ github.sha }}'

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GKE_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy application to GKE
        run: kubectl apply -f k8s/deployment.yml -f k8s/service.yml
